#
# Copyright (C) ST-Ericsson SA 2010
# Author: Martin Hovang (martin.xm.hovang@stericsson.com)
# License terms: GNU General Public License (GPL) version 2
#

obj-$(CONFIG_TEE_SUPPORT) += tee_service.o
obj-$(CONFIG_TEE_SUPPORT) += tee_driver.o
obj-$(CONFIG_TEE_SUPPORT) += tee_supp_com.o
obj-$(CONFIG_TEE_SUPPORT) += tee_mem.o
obj-$(CONFIG_TEE_SUPPORT) += tee_v017.o
obj-$(CONFIG_TEE_SUPPORT) += tee_v100.o
obj-$(CONFIG_TEE_SUPPORT) += tee_ioctl.o
